baseurl = "https://koderkow.rbind.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Kyle Harris"
theme = "hugo-theme-dream"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# copyright = ""

# googleAnalytics = ""

disqusShortname = "KoderKow"

# enableRobotsTXT = true

[params]
  highlightjsVersion = "10.1.2"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"
  background = "#252323"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Kyle"
  # description = ""
  # avatar = "/img/discord_icon.png"
  # avatar = "https://pbs.twimg.com/profile_images/1143728869851238402/1SoVACjN_400x400.jpg"
  motto = "And that's why I turned one of your pistols into a banana."

  # rss = true

  # utterancesRepo = ""
  
  email = "KoderKow@gmail.com"
  twitter = "KoderKow"
  # facebook = ""
  # instagram = ""
  linkedin = "KyleWHarris"
  github = "KoderKow"
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2018

  # favicon = "/favicon.ico"

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true

[params.gravatar]
    email = "koderkow@gmail.com"   #uncomment and insert your email address to use gravatar