[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENV = "production hugo --gc --minify"