---
title: "Open Source Contributions"
output:
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
library(dplyr)
library(glue)
library(kowr)
library(knitr)
library(kableExtra)

d <-
  list(
    repo_name = c(
      "tidylog",
      "golem",
      "kowr",
      "togglr",
      "shinydashboardPlus"
    ),
    repo_url = c(
      "https://github.com/elbersb/tidylog/",
      "https://github.com/ThinkR-open/golem",
      "https://github.com/KoderKow/kowr",
      "https://github.com/ThinkR-open/togglr",
      "https://github.com/RinteRface/shinydashboardPlus"
    ),
    repo_type = c(
      "R Package (CRAN)",
      "R Package (CRAN)",
      "R Package (GitHub)",
      "R Package (CRAN)",
      "R Package (CRAN)"
    ),
    contribution_url = c(
      "https://github.com/elbersb/tidylog/pulls?q=is%3Apr+author%3Akoderkow+is%3Aclosed+",
      "https://github.com/ThinkR-open/golem/pulls?q=is%3Apr+author%3Akoderkow+is%3Aclosed+",
      "https://github.com/koderkow/kowr/pulls?q=is%3Apr+author%3Akoderkow+is%3Aclosed+",
      "https://github.com/ThinkR-open/togglr/pulls?q=is%3Apr+author%3Akoderkow+is%3Aclosed+",
      "https://github.com/RinteRface/shinydashboardPlus/pulls?q=is%3Apr+author%3Akoderkow+is%3Aclosed+"
    ),
    year = c(
      2019,
      2020,
      2019,
      2020,
      2020
    ),
    comments = c(
      "First contribution ever! Add more functionality and clarity",
      "Added run_dev function and addin",
      "Personal R package",
      "Bug fix for accounts with no project entries",
      "Made user card more flexible"
    ),
    info = c(
      "Provide feedback about dplyr and tidyr operations",
      "An opinionated framework for building production-grade shiny applications",
      "Utility functions",
      "An R and Rstudio wrapper for toggl Api",
      "extensions for shinydashboard"
    )
  ) %>% 
  bind_rows() %>% 
  arrange(year, repo_name)
```

```{r, echo=FALSE}
d %>% 
  mutate(
    repo = glue("[{repo_name}]({repo_url})"),
    year = glue("[{year}]({contribution_url})")
  ) %>% 
  select(
    repo,
    repo_type,
    info,
    year
  ) %>% 
  snake_to() %>%
  kable(align = "l", padding = 2)
```

